# Copy đúng thư mục web
COPY CleanMate.CleanerWeb/ CleanMate.CleanerWeb/

# ✅ Copy thêm thư mục dùng chung (Models, DataContext,...)
COPY CleanMate.Api/Models CleanMate.Api/Models
COPY CleanMate.Api/Data CleanMate.Api/Data

WORKDIR /src/CleanMate.CleanerWeb
RUN dotnet publish -c Release -o /app/publish --no-restore --no-dependencies
